name: Code checking.
on:
  push:
    branches: [feat/backend, dev]
  pull_request: 
    branches: [dev]

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: action/checkout@v4
            - name: tests
              uses: action/setup-python@v4
              with: 
                python-version: 3.12
            - name: install dependencies
              run: |
                python -m pip install --upgrade pip
                pipx install poetry
                poetry install
            - name: tests
              run: pytest

                
