name: Code checking.
on:
  push:
    branches: [feat/backend, dev]
  pull_request: 
    branches: [dev]

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: tests
              uses: actions/setup-python@v4
              with: 
                python-version: "3.10.12"
            - name: install dependencies
              run: |
                python -m pip install --upgrade pip
                pipx install poetry
                poetry install
                poetry shell
            - name: tests
              run: pytest

                
